// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgI8pHMljCToiaKBbVEsMSvbWigduzvr4',
    appId: '1:1077010706329:web:258f4ba95357e6d2de2d08',
    messagingSenderId: '1077010706329',
    projectId: 'bleagna',
    authDomain: 'bleagna.firebaseapp.com',
    storageBucket: 'bleagna.appspot.com',
    measurementId: 'G-VWGCJLR90G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAofOiWYuH8I_nLyozD9kBdJtizJqkIi8s',
    appId: '1:1077010706329:android:bc27a50b70daf74dde2d08',
    messagingSenderId: '1077010706329',
    projectId: 'bleagna',
    storageBucket: 'bleagna.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKARbYrlawcY_c2nOF966QCOmi9Zna_4s',
    appId: '1:1077010706329:ios:6d7e430e9b2d5e03de2d08',
    messagingSenderId: '1077010706329',
    projectId: 'bleagna',
    storageBucket: 'bleagna.appspot.com',
    iosBundleId: 'com.example.blesslagna',
  );
}
